services:
    app: &app_service
        build:
            context: ./_docker/swoole
            target: dev
        volumes:
            - ./:/app
        environment:
            DATABASE_URL: "postgresql://postgres:root@database:5432/demo?serverVersion=16&charset=utf8"
            APP_ENV: dev
            APP_RUNTIME: "Runtime\\Swoole\\Runtime"
            SWOOLE_HOST: "0.0.0.0"
            SWOOLE_PORT: 9501
        depends_on:
            - database

    fpm:
        build:
            context: ./_docker/fpm
            target: dev
        volumes:
            - ./:/app
            - ./_docker/fpm/fpm.ini:/usr/local/etc/php-fpm.d/zz-app.conf
            - ./_docker/fpm/php.ini:/usr/local/etc/php/conf.d/prod.ini
        environment:
            DATABASE_URL: "postgresql://postgres:root@database:5432/demo?serverVersion=16&charset=utf8"
            APP_ENV: dev

    web:
        image: nginx:1.25-alpine
        volumes:
            - ./_docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "80:80"
            - "8080:8080"
        depends_on:
            - app

    ###> doctrine/doctrine-bundle ###
    database:
        image: postgres:${POSTGRES_VERSION:-16}-alpine
        environment:
            POSTGRES_DB: ${POSTGRES_DB:-demo}
            # You should definitely change the password in production
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-root}
            POSTGRES_USER: ${POSTGRES_USER:-postgres}
        volumes:
            - database_data:/var/lib/postgresql/data:rw

    ###< doctrine/doctrine-bundle ###

    # db:
    #     image: postgres:16-alpine
    #     environment:
    #         POSTGRES_DB: demo
    #         POSTGRES_PASSWORD: root
    #         POSTGRES_USER: postgres
    #     volumes:
    #         - database_data:/var/lib/postgresql/data:rw

    migrations:
        <<: *app_service
        command:
            [
                "php",
                "bin/console",
                "doctrine:migrations:migrate",
                "--no-interaction",
            ]
        restart: on-failure

    wrk:
        container_name: "benchmark_tool"
        image: williamyeh/wrk
        volumes:
            - ./_docker/wrk/bench.sh:/app/bench.sh
        working_dir: /app
        entrypoint: /app/bench.sh
        depends_on:
            - fpm
            - app
        restart: no

volumes:
    ###> doctrine/doctrine-bundle ###
    database_data:
###< doctrine/doctrine-bundle ###
